"""add_bio_to_users

Revision ID: 41bf5b20b59a
Revises: 7e4d68bb2185
Create Date: 2026-07-27 13:32:02.019735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41bf5b20b59a'
down_revision: Union[str, Sequence[str], None] = '7e4d68bb2185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_messages_client_msg_id'), 'messages', type_='unique')
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.create_unique_constraint(op.f('uq_messages_client_msg_id'), 'messages', ['client_msg_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
