"""Add is_premium flag to blog model

Revision ID: 73cb0b7bb88b
Revises: 82c7b10ddbba
Create Date: 2026-07-21 18:04:26.584316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73cb0b7bb88b'
down_revision: Union[str, Sequence[str], None] = '82c7b10ddbba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('is_premium', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'is_premium')
    # ### end Alembic commands ###
