"""add_role_to_users

Revision ID: 8616736ea14f
Revises: e64a0e870841
Create Date: 2026-07-17 18:22:18.966147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8616736ea14f'
down_revision: Union[str, Sequence[str], None] = 'e64a0e870841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'WRITER', 'USER', name='user_role', native_enum=False), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
